# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 04:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apt_Name', models.CharField(max_length=200)),
                ('Apt_Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment_info_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apartment_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Apartment')),
                ('Board_Kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Category')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Community_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to='pictures/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Category')),
                ('Image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Rent_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Category')),
                ('Image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Category')),
                ('Image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Selling_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Category')),
                ('Image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Image')),
            ],
        ),
        migrations.AddField(
            model_name='community_comment',
            name='Image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Image'),
        ),
        migrations.AddField(
            model_name='community',
            name='Image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Image'),
        ),
        migrations.AddField(
            model_name='apartment_info_comment',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Category'),
        ),
        migrations.AddField(
            model_name='apartment_info_comment',
            name='Image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Image'),
        ),
        migrations.AddField(
            model_name='apartment_info',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Category'),
        ),
        migrations.AddField(
            model_name='apartment_info',
            name='Image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Image'),
        ),
    ]
